// Optional canonical W2 operator gate.
//
// Set ESCHA_W2_FIXTURE to the compact binary generated by
// C:\Den\den-nvfp4-optimizations\tools\make_escha_w2_operator_fixture.py.
// The fixture holds real canonical K2/K3 payload crops and independently
// generated expected F32 outputs.  No fixture means a normal no-op CTest run.

#include "ggml.h"
#include "ggml-backend.h"
#include "ggml-cpu.h"
#include "ggml-cuda.h"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

namespace {

struct fixture_record {
    std::string name;
    int32_t k = 0;
    int32_t ic = 0;
    int32_t oc = 0;
    int32_t rows = 0;
    std::vector<int16_t> code;
    std::vector<int16_t> dep;
    std::vector<ggml_fp16_t> rin;
    std::vector<ggml_fp16_t> rout;
    std::vector<float> s_in;
    std::vector<float> s_out;
    std::vector<float> x;
    // v2 checkpoints: rotation boundary (F16) and pre-finalization MMA (F32).
    // v1 records leave these vectors empty and retain only expected.
    std::vector<ggml_fp16_t> expected_rot;
    std::vector<float> expected_mma;
    std::vector<float> expected;
};

template<typename T>
bool read_scalar(std::ifstream & in, T * value) {
    in.read(reinterpret_cast<char *>(value), sizeof(*value));
    return in.good();
}

template<typename T>
bool read_vector(std::ifstream & in, std::vector<T> * values, size_t count) {
    values->resize(count);
    in.read(reinterpret_cast<char *>(values->data()), static_cast<std::streamsize>(count*sizeof(T)));
    return in.good();
}

bool read_record(std::ifstream & in, fixture_record * r, uint32_t version) {
    uint32_t name_len = 0;
    if (!read_scalar(in, &name_len) || name_len == 0 || name_len > 1024) {
        return false;
    }
    r->name.resize(name_len);
    in.read(r->name.data(), name_len);
    if (!in.good() || !read_scalar(in, &r->k) || !read_scalar(in, &r->ic) ||
            !read_scalar(in, &r->oc) || !read_scalar(in, &r->rows)) {
        return false;
    }
    if ((r->k != 2 && r->k != 3) || r->ic <= 0 || r->oc <= 0 || r->rows <= 0 ||
            r->ic > (1 << 20) || r->oc > (1 << 20) || r->rows > (1 << 16) ||
            r->ic % 128 || r->oc % 128 || r->ic % 16 || r->oc % 16) {
        return false;
    }
    const size_t code_count = static_cast<size_t>(r->ic/16)*(r->oc/16)*16*r->k;
    const size_t in_count = static_cast<size_t>(r->ic);
    const size_t out_count = static_cast<size_t>(r->oc);
    const size_t x_count = in_count*r->rows;
    const size_t y_count = out_count*r->rows;
    if (!(read_vector(in, &r->code, code_count) &&
            read_vector(in, &r->dep, 256*16) &&
            read_vector(in, &r->rin, in_count) &&
            read_vector(in, &r->rout, out_count) &&
            read_vector(in, &r->s_in, in_count) &&
            read_vector(in, &r->s_out, out_count) &&
            read_vector(in, &r->x, x_count))) {
        return false;
    }
    if (version >= 2) {
        if (!read_vector(in, &r->expected_rot, x_count) ||
                !read_vector(in, &r->expected_mma, y_count)) {
            return false;
        }
        for (size_t i = 0; i < r->expected_rot.size(); ++i) {
            if (!std::isfinite(ggml_fp16_to_fp32(r->expected_rot[i]))) {
                return false;
            }
        }
        for (float value : r->expected_mma) {
            if (!std::isfinite(value)) {
                return false;
            }
        }
    }
    return read_vector(in, &r->expected, y_count);
}

bool close_enough(const std::vector<float> & got, const std::vector<float> & want,
                  const char * backend, const fixture_record & r, float rel_tol) {
    if (got.size() != want.size()) {
        std::fprintf(stderr, "FAIL %s %s: output size mismatch\n", backend, r.name.c_str());
        return false;
    }
    float max_abs = 0.0f;
    size_t worst = 0;
    for (size_t i = 0; i < got.size(); ++i) {
        if (!std::isfinite(got[i])) {
            std::fprintf(stderr, "FAIL %s %s: nonfinite output at %zu\n", backend, r.name.c_str(), i);
            return false;
        }
        const float diff = std::fabs(got[i] - want[i]);
        if (diff > max_abs) {
            max_abs = diff;
            worst = i;
        }
        if (diff > rel_tol*(1.0f + std::fabs(want[i]))) {
            std::fprintf(stderr, "FAIL %s %s: index=%zu got=%g expected=%g abs=%g tol=%g\n",
                    backend, r.name.c_str(), i, got[i], want[i], diff,
                    rel_tol*(1.0f + std::fabs(want[i])));
            return false;
        }
    }
    std::fprintf(stderr, "PASS %s %s: max_abs=%g at %zu\n", backend, r.name.c_str(), max_abs, worst);
    return true;
}

size_t cpu_context_bytes(const fixture_record & r) {
    // CPU tensors own their payload in the ggml context.  Production K3 code
    // is tens of MiB, so the old tiny default used by synthetic unit tests is
    // invalid for this canonical fixture gate.
    const size_t payload = r.code.size()*sizeof(int16_t) + r.dep.size()*sizeof(int16_t) +
        r.rin.size()*sizeof(ggml_fp16_t) + r.rout.size()*sizeof(ggml_fp16_t) +
        r.s_in.size()*sizeof(float) + r.s_out.size()*sizeof(float) +
        r.x.size()*sizeof(float) + r.expected.size()*sizeof(float);
    return payload + (1 << 20);
}

bool compute_cpu(const fixture_record & r, bool use_qwen38_route) {
    ggml_init_params params = { cpu_context_bytes(r), nullptr, false };
    ggml_context * ctx = ggml_init(params);
    if (!ctx) {
        return false;
    }
    ggml_tensor * code = ggml_new_tensor_3d(ctx, GGML_TYPE_I16, 16*r.k, r.oc/16, r.ic/16);
    ggml_tensor * rin = ggml_new_tensor_1d(ctx, GGML_TYPE_F16, r.ic);
    ggml_tensor * rout = ggml_new_tensor_1d(ctx, GGML_TYPE_F16, r.oc);
    ggml_tensor * s_in = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, r.ic);
    ggml_tensor * s_out = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, r.oc);
    ggml_tensor * dep = ggml_new_tensor_2d(ctx, GGML_TYPE_I16, 16, 256);
    ggml_tensor * x = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, r.ic, r.rows);
    ggml_tensor * result = use_qwen38_route
        ? ggml_escha_linear_qwen38_w2(ctx, code, rin, rout, s_in, s_out, dep, x)
        : ggml_escha_linear(ctx, code, rin, rout, s_in, s_out, dep, x);
    std::memcpy(code->data, r.code.data(), r.code.size()*sizeof(int16_t));
    std::memcpy(rin->data, r.rin.data(), r.rin.size()*sizeof(ggml_fp16_t));
    std::memcpy(rout->data, r.rout.data(), r.rout.size()*sizeof(ggml_fp16_t));
    std::memcpy(s_in->data, r.s_in.data(), r.s_in.size()*sizeof(float));
    std::memcpy(s_out->data, r.s_out.data(), r.s_out.size()*sizeof(float));
    std::memcpy(dep->data, r.dep.data(), r.dep.size()*sizeof(int16_t));
    std::memcpy(x->data, r.x.data(), r.x.size()*sizeof(float));
    ggml_cgraph * graph = ggml_new_graph_custom(ctx, 16, false);
    ggml_build_forward_expand(graph, result);
    ggml_backend_t backend = ggml_backend_cpu_init();
    const ggml_status status = ggml_backend_graph_compute(backend, graph);
    std::vector<float> got(r.expected.size());
    if (status == GGML_STATUS_SUCCESS) {
        std::memcpy(got.data(), result->data, got.size()*sizeof(float));
    }
    ggml_backend_free(backend);
    ggml_free(ctx);
    return status == GGML_STATUS_SUCCESS && close_enough(got, r.expected, "CPU", r, 3e-4f);
}

bool compute_cuda(const fixture_record & r, bool use_qwen38_route) {
    ggml_init_params params = { 1 << 20, nullptr, true };
    ggml_context * ctx = ggml_init(params);
    if (!ctx) {
        return false;
    }
    ggml_backend_t backend = ggml_backend_cuda_init(0);
    if (!backend) {
        ggml_free(ctx);
        return false;
    }
    ggml_tensor * code = ggml_new_tensor_3d(ctx, GGML_TYPE_I16, 16*r.k, r.oc/16, r.ic/16);
    ggml_tensor * rin = ggml_new_tensor_1d(ctx, GGML_TYPE_F16, r.ic);
    ggml_tensor * rout = ggml_new_tensor_1d(ctx, GGML_TYPE_F16, r.oc);
    ggml_tensor * s_in = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, r.ic);
    ggml_tensor * s_out = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, r.oc);
    ggml_tensor * dep = ggml_new_tensor_2d(ctx, GGML_TYPE_I16, 16, 256);
    ggml_tensor * x = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, r.ic, r.rows);
    ggml_tensor * result = use_qwen38_route
        ? ggml_escha_linear_qwen38_w2(ctx, code, rin, rout, s_in, s_out, dep, x)
        : ggml_escha_linear(ctx, code, rin, rout, s_in, s_out, dep, x);
    ggml_backend_buffer_t buffer = ggml_backend_alloc_ctx_tensors(ctx, backend);
    const bool ready = result != nullptr && buffer != nullptr;
    if (ready) {
        ggml_backend_tensor_set(code, r.code.data(), 0, ggml_nbytes(code));
        ggml_backend_tensor_set(rin, r.rin.data(), 0, ggml_nbytes(rin));
        ggml_backend_tensor_set(rout, r.rout.data(), 0, ggml_nbytes(rout));
        ggml_backend_tensor_set(s_in, r.s_in.data(), 0, ggml_nbytes(s_in));
        ggml_backend_tensor_set(s_out, r.s_out.data(), 0, ggml_nbytes(s_out));
        ggml_backend_tensor_set(dep, r.dep.data(), 0, ggml_nbytes(dep));
        ggml_backend_tensor_set(x, r.x.data(), 0, ggml_nbytes(x));
    }
    ggml_cgraph * graph = ready ? ggml_new_graph_custom(ctx, 16, false) : nullptr;
    if (graph) {
        ggml_build_forward_expand(graph, result);
    }
    const ggml_status status = graph ? ggml_backend_graph_compute(backend, graph) : GGML_STATUS_FAILED;
    std::vector<float> got(r.expected.size());
    if (status == GGML_STATUS_SUCCESS) {
        ggml_backend_tensor_get(result, got.data(), 0, ggml_nbytes(result));
    }
    if (buffer) {
        ggml_backend_buffer_free(buffer);
    }
    ggml_backend_free(backend);
    ggml_free(ctx);
    return status == GGML_STATUS_SUCCESS && close_enough(got, r.expected, "CUDA", r, 8e-4f);
}

} // namespace

int main() {
    const char * path = std::getenv("ESCHA_W2_FIXTURE");
    if (!path || !*path) {
        std::fprintf(stderr, "SKIP: set ESCHA_W2_FIXTURE for canonical W2 operator gate\n");
        return 0;
    }
    std::ifstream in(path, std::ios::binary);
    char magic[4] = {};
    uint32_t version = 0;
    uint32_t records = 0;
    if (!in.read(magic, sizeof(magic)) || std::memcmp(magic, "EW2F", 4) != 0 ||
            !read_scalar(in, &version) || !read_scalar(in, &records) ||
            (version != 1 && version != 2) || records == 0 || records > 16) {
        std::fprintf(stderr, "FAIL: invalid ESCHA fixture %s\n", path);
        return 1;
    }
    const bool cuda_present = ggml_backend_cuda_get_device_count() > 0;
    const bool qwen38_route =
        version >= 2 && std::getenv("DEN_ESCHA_QWEN38_SM120") != nullptr;
    for (uint32_t i = 0; i < records; ++i) {
        fixture_record record;
        if (!read_record(in, &record, version)) {
            std::fprintf(stderr, "FAIL: malformed fixture record %u\n", i);
            return 1;
        }
        if (!compute_cpu(record, qwen38_route) ||
            (cuda_present && !compute_cuda(record, qwen38_route))) {
            return 1;
        }
    }
    std::fprintf(stderr, "PASS: canonical ESCHA W2 operator fixture (%u records)\n", records);
    return 0;
}
