#!/usr/bin/env python3
"""embed_omma_cubin.py — Generate nvfp4_omma_cubin_data.h from nvfp4_omma.cubin.

Embeds the OMMA.SF.16864 cubin as a C array so it can be loaded at runtime via
cuModuleLoadData() regardless of the process CWD (robust dispatch wiring).

Usage:
  python3 embed_omma_cubin.py <input.cubin> <output.h>
"""
import sys


def main():
    if len(sys.argv) != 3:
        print('usage: embed_omma_cubin.py <input.cubin> <output.h>')
        return 1
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, 'rb') as f:
        data = f.read()
    lines = ['/* Auto-generated by embed_omma_cubin.py — do not edit. */',
             '#pragma once',
             'static const unsigned char nvfp4_omma_cubin[] = {']
    n = len(data)
    for i in range(0, n, 12):
        chunk = data[i:i + 12]
        lines.append('    ' + ','.join(f'0x{b:02x}' for b in chunk) + ',')
    lines.append('};')
    lines.append(f'static const unsigned int nvfp4_omma_cubin_len = {n};')
    lines.append('')
    with open(dst, 'w') as f:
        f.write('\n'.join(lines))
    print(f'embedded {n} bytes -> {dst}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
